spring:
  servlet:
    multipart:
      max-file-size: 1000MB # 最大支持文件大小
      max-request-size: 5000MB # 最大支持请求大小

dist:
  minio:
    config:
      enabled: true
      secure: false
      endpoint: http://127.0.0.1
      port: 9000
      accessKey: minioadmin
      secretKey: minioadmin
      default-bucket: default # 可选，仅支持小写字母,长度必须大于3个字符,会自动创建
